name: gastos_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  intl: ^0.16.1
  flutter_custom_clippers: ^1.1.1
  google_fonts: ^1.1.0
  flutter_slidable: "^0.5.4"
  sqflite: ^1.3.0
  path: ^1.6.4
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Do Hyeon
      fonts:
        - asset: fonts/DoHyeon-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

